#!/usr/bin/env python3
"""Fail-closed, source-safe production RC01 verification on the exact BOILER XML.

The 147-slot starting state and the counterfactual are immutable historical
records; neither is regenerated by the changed production implementation.
"""
from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
for directory in (ROOT, ROOT / "src"):
    if str(directory) not in sys.path:
        sys.path.insert(0, str(directory))

from scripts.evidence import p1_g2_baseline_diagnostics as baseline
from scripts.evidence import p1_g2_post_rc02_review as safe
from scripts.evidence import p1_g2_rc02_boiler_counterfactual as keys
from scripts.evidence import p1_g2_rc02_production_verification as projection
from sto.core.engine.validate import validate_result, VALIDATOR_PROFILE
from sto.core.engine.forward import FORWARD_PASS_PROFILE
from sto.core.engine.backward import BACKWARD_PASS_PROFILE
from sto.core.engine.result import RESULT_PROFILE

SCHEMA = "sto-p1-g2-rc01-production-verification-v1"
BASE_MAIN = "a899a0c3b76f21016be89ff2fd0111065b81a4c6"
BOILER_BYTES = 3_361_935
BOILER_SHA = "e9b9b7994cc5cc50479807b82c452da742a91de9f7de52b172a6be6f4f399c70"
ROOTS = {"L0070", "L0075", "L0080", "L0083", "L0084", "L0114",
         "L0127", "L0148", "L0157", "L0190"}
SURVIVING = {("L0407", "free_float"), ("L0407", "total_float"),
             ("L0411", "total_float")}
EVIDENCE = ROOT / "docs/evidence"
HISTORICAL = EVIDENCE / "p1-g2-post-rc02-review-2026-09-25.json"
COUNTERFACTUAL = EVIDENCE / "p1-g2-rc01-boiler-counterfactual-2026-09-28.json"
IMPACT = EVIDENCE / "p1-g2-rc01-boiler-counterfactual-impact-2026-09-28.json"
R6 = EVIDENCE / "p1-g2-rc01-networked-native-v3-r6-inconclusive-return-2026-09-28.json"
ATTESTATION = EVIDENCE / "p1-g2-rc01-networked-native-v3-r6-operator-attestation-2026-09-28.md"
IMPACT_SHA = "ec2adf6b5f07b293fb72865963fc34d97870256385e160be339b70b69b029b96"
R6_SHA = "540b2fb3664c1884ba5d928adf52e5be0dc149941bb3e7f2c2478e595843f7d2"
ATTESTATION_SHA = "5310a6b2e138eec60ed808529f2ad193140a75c4e8890a3d87d00bb4b4e6db62"


class VerificationError(ValueError):
    """The exact controlled production acceptance contract did not hold."""


def pinned(path: Path, expected_sha: str) -> dict:
    payload = path.read_bytes()
    if hashlib.sha256(payload).hexdigest() != expected_sha:
        raise VerificationError(f"historical evidence identity changed: {path.name}")
    return json.loads(payload)


def build_record(source: Path) -> dict:
    payload = source.read_bytes()
    if len(payload) != BOILER_BYTES or hashlib.sha256(payload).hexdigest() != BOILER_SHA:
        raise VerificationError("exact controlled BOILER baseline identity differs")
    current_sha = "9a3ef68637b6e213188400f05fdca9bd216eebfbafa100f10f817623f5b8f3d3"
    measured_sha = "30be4ebaac5aa6a6e43aa8d4fa08a90fd531bc506d6b068463a3bbcf4052675e"
    current = pinned(HISTORICAL, current_sha)
    measured = pinned(COUNTERFACTUAL, measured_sha)
    impact = pinned(IMPACT, IMPACT_SHA)
    r6 = pinned(R6, R6_SHA)
    if hashlib.sha256(ATTESTATION.read_bytes()).hexdigest() != ATTESTATION_SHA:
        raise VerificationError("R6 operator attestation identity changed")
    if (impact["measured_result"]["sha256"] != measured_sha
        or r6["classification"]["verdict"] != "V3_NETWORKED_ASSIGNMENT_ENVELOPE_INCONCLUSIVE"
        or r6["decision"]["native_v3_supported"] is not False
        or r6["decision"]["production_rc01_correction_authorized"] is not False
        or current["current_inventory"]["slots"] != 147
        or current["current_inventory"]["leaves"] != 39
        or current["current_inventory"]["by_group"] != {"G2-RC01": 144, "G2-RC03": 3}
        or measured["before"]["slots"] != 147
        or measured["movement"]["rc01_closed"] != 144
        or set(current["current_inventory"]["root_leaf_ids_by_group"]["G2-RC01"]) != ROOTS
        or measured["decision"]["production_rc01_correction_authorized"] is not False):
        raise VerificationError("pinned historical starting/counterfactual contract differs")
    before_rows = current["current_recomputation"]["mismatches"]
    before = {(row["leaf_id"], row["field"]): row for row in before_rows}
    rc01 = {key for key, row in before.items() if row["diagnostic_group"] == "G2-RC01"}
    if (len(before) != 147 or len(rc01) != 144
        or set(before) - rc01 != SURVIVING
        or sorted([list(key) for key in before]) != measured["before"]["keys"]):
        raise VerificationError("starting 147-slot mismatch keys differ")

    schedule = baseline._load(payload)
    calculation = baseline._calculate(schedule)
    observed = baseline._observed(baseline._activities(schedule))
    calculated = baseline._engine(schedule, calculation.result)
    leaf_by_uid, _, source_by_leaf = keys._leaf_maps(schedule)
    leaf_by_source = {source_uid: leaf for leaf, source_uid in source_by_leaf.items()}
    if set(calculated) != {baseline._source_uid(row) for row in schedule.activities
                           if row.uid in calculation.plan.network.activity_by_uid()}:
        raise VerificationError("calculated leaf cohort differs from network")
    excluded = {row.uid for row in calculation.plan.excluded if row.kind == "activity"}
    scheduled = set(calculation.plan.network.activity_by_uid())
    if (scheduled & excluded or scheduled | excluded != {row.uid for row in schedule.activities}
        or len(scheduled) != 451 or len(excluded) != 9
        or {row.code for row in calculation.plan.excluded if row.kind == "activity"}
        != {"ACTIVITY_INACTIVE"}):
        raise VerificationError("scheduled/excluded partition is not exact")
    new_keys = keys._mismatch_keys(observed, calculated, leaf_by_source)
    new = new_keys - set(before)
    if (new_keys != SURVIVING or new or rc01 & new_keys
        or sorted([list(key) for key in new_keys]) != measured["after"]["keys"]):
        raise VerificationError("production did not reproduce exact 147→3 movement")
    def delta(key):
        leaf, field = key
        src = source_by_leaf[leaf]
        index = baseline.RESULT_FIELDS.index(field)
        return keys._delta(observed[src][index], calculated[src][index])
    if any(delta(key) != before[key]["sto_minus_source_seconds"] for key in SURVIVING):
        raise VerificationError("surviving RC03 delta changed")
    first = {key for key in rc01 if before[key]["dependency_role"] == "FIRST_DIVERGENCE"}
    if len(first) != 22:
        raise VerificationError("RC01 first-divergence inventory changed")
    actual_fields = Counter(field for _, field in new_keys)
    before_fields = Counter(field for _, field in before)
    if any(impact["by_field"][field] != {
        "before": before_fields[field], "after": actual_fields[field],
        "closed": before_fields[field] - actual_fields[field], "new": 0,
    } for field in baseline.RESULT_FIELDS):
        raise VerificationError("by-field movement differs from counterfactual")
    root_movement = {leaf: {
        "before_slots": sum(key[0] == leaf for key in before),
        "after_slots": sum(key[0] == leaf for key in new_keys),
        "closed_slots": sum(key[0] == leaf for key in before) - sum(key[0] == leaf for key in new_keys),
        "first_divergence_closed": sum(key[0] == leaf for key in first),
    } for leaf in sorted(ROOTS)}
    if root_movement != impact["current_root_movement"]:
        raise VerificationError("ten-root closure differs from counterfactual")
    eligible = {leaf_by_uid[row.uid] for row in calculation.plan.network.activities
                if row.assignment_envelope is not None}
    if eligible != ROOTS:
        raise VerificationError("bounded BOILER assignment eligibility differs from ten roots")
    violations = validate_result(calculation.plan.network, calculation.forward,
                                 calculation.backward, calculation.floats)
    if violations:
        raise VerificationError(f"independent production validator: {len(violations)} violations")
    _, projection_sha = projection._projection(calculated, leaf_by_source)
    if source.read_bytes() != payload:
        raise VerificationError("BOILER source bytes changed")
    return {
        "schema": SCHEMA, "starting_main": BASE_MAIN,
        "pr64_merge_commit": BASE_MAIN,
        "production_files": [
            "src/sto/core/engine/backward.py", "src/sto/core/engine/forward.py",
            "src/sto/core/engine/network.py", "src/sto/core/engine/plan.py",
            "src/sto/core/engine/result.py", "src/sto/core/engine/validate.py",
            "src/sto/core/model/migrate/sto_v011.py", "src/sto/legacy/mspdi_resources.py",
        ],
        "boiler": {"bytes": len(payload), "sha256": BOILER_SHA},
        "historical_evidence": {
            "post_rc02_sha256": current_sha, "counterfactual_sha256": measured_sha,
            "impact_sha256": IMPACT_SHA,
            "r6_inconclusive_sha256": R6_SHA,
            "r6_operator_attestation_sha256": ATTESTATION_SHA,
            "r6_verdict": "V3_NETWORKED_ASSIGNMENT_ENVELOPE_INCONCLUSIVE",
            "historical_production_authorization": False,
        },
        "profiles": {
            "old": {"forward": "sto-forward-pass-v4", "backward": "sto-backward-pass-v8",
                    "result": "sto-result-v3", "validator": "sto-validator-v4"},
            "new": {"forward": FORWARD_PASS_PROFILE, "backward": BACKWARD_PASS_PROFILE,
                    "result": RESULT_PROFILE, "validator": VALIDATOR_PROFILE},
        },
        "network_fingerprint": calculation.plan.network.fingerprint(),
        "production_projection_sha256": projection_sha,
        "before": {"slots": len(before), "leaves": 39, "by_group": {"G2-RC01": 144, "G2-RC03": 3}},
        "after": {"slots": len(new_keys), "by_group": {"G2-RC01": 0, "G2-RC03": 3,
                                                 "G2-RC02": 0, "G2-RC04": 0},
                  "remaining_keys": [list(key) for key in sorted(new_keys)]},
        "movement": {"closed_rc01": len(rc01 - new_keys),
                     "closed_first_divergences": len(first), "root_movement": root_movement,
                     "by_field": {field: impact["by_field"][field] for field in baseline.RESULT_FIELDS},
                     "new_keys": [], "worsened_keys": [], "non_rc01_movement": 0},
        "disposition": {"scheduled_leaves": len(scheduled), "excluded_activities": len(excluded),
                        "partition_exact": True, "eligible_root_leaf_ids": sorted(eligible)},
        "validator": {"profile": VALIDATOR_PROFILE, "violations": []},
        "optional_real_fixtures": {"KILN": "UNAVAILABLE_NOT_RUN",
                                   "CALCINER": "UNAVAILABLE_NOT_RUN"},
        "validation": {"required_mode_exact_BOILER": "PASS",
                       "hosted_ci": "PENDING_PUBLISHED_PR_HEAD",
                       "codex_review": "PENDING_PUBLISHED_PR_HEAD"},
        "decision": {"classification": "RC01_PRODUCTION_CORRECTION_VERIFIED",
                     "p1_g2_closed": False, "p1_gate": "4/5 IN PROGRESS", "p2_started": False},
    }


def serialize(record: dict) -> str:
    return json.dumps(record, sort_keys=True, indent=2) + "\n"


def protected(source: Path) -> dict[str, Path]:
    return {"BOILER baseline": source, **{f"evidence:{p.name}": p
            for p in EVIDENCE.iterdir() if p.is_file()}}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("boiler", type=Path)
    destination = parser.add_mutually_exclusive_group(required=True)
    destination.add_argument("--check", type=Path)
    destination.add_argument("--output", type=Path)
    args = parser.parse_args()
    sources = protected(args.boiler)
    if args.output is not None:
        safe.refuse_output_alias(args.output, sources)
    contents = serialize(build_record(args.boiler))
    if args.check is not None:
        if args.check.read_bytes() != contents.encode():
            raise VerificationError("committed production evidence differs")
    else:
        safe.write_output_safely(args.output, contents, sources)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
